[workspace]

members = [
    "goko",
    "pygoko",
    "pointcloud",
    "serve_goko",
]
default-members = [
    "goko", 
    "pointcloud",
    "serve_goko",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3